AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

  CacheRootDirectory: /tmp
  AllowSymlinksInCacheRootDirectory: true

  Exclude:
    - 'bin/*'
    - 'tmp/**/*'

Layout/ParameterAlignment:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'

Naming/FileName:
  Exclude:

Naming/MethodParameterName:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
