AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

  CacheRootDirectory: /tmp
  AllowSymlinksInCacheRootDirectory: true

  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'spec/**/*'

Layout/LineLength:
  Max: 150

Layout/ParameterAlignment:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'

Naming/FileName:
  Exclude:

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
